version: '3'
services:
  mysql:
    build: docker/mysql
    container_name: mysql8
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysql", "--user=$MYSQL_USER", "--password=$MYSQL_ROOT_PASSWORD", "-e", "SHOW DATABASES;"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy